import type { Question } from "@/lib/types";

/** 常识判断样例题 15 */
export const commonQuestions: Question[] = [
  {
    id: "common-001",
    module: "common",
    type: "single-choice",
    stem: "我国宪法规定，中华人民共和国的一切权力属于：",
    options: ["公民", "人民", "全国人大", "中国共产党"],
    answer: 1,
    analysis: "宪法第二条：一切权力属于人民。人民通过人大行使国家权力。公民是法律概念，人民是政治概念。",
    tags: ["宪法", "政治"],
  },
  {
    id: "common-002",
    module: "common",
    type: "single-choice",
    stem: "下列属于行政处罚的是：",
    options: ["罚款", "罚金", "赔偿损失", "支付违约金"],
    answer: 0,
    analysis:
      "罚款是行政处罚；罚金是刑罚；赔偿损失是民事责任；违约金是民事责任。",
    tags: ["行政法", "法律责任"],
  },
  {
    id: "common-003",
    module: "common",
    type: "single-choice",
    stem: "光年是什么物理量的单位？",
    options: ["时间", "长度", "速度", "亮度"],
    answer: 1,
    analysis: "光年是光在真空中一年走过的距离，长度单位，约 9.46 万亿千米。",
    tags: ["科技常识", "物理"],
  },
  {
    id: "common-004",
    module: "common",
    type: "single-choice",
    stem: "「但愿人长久，千里共婵娟」中的「婵娟」指：",
    options: ["月亮", "太阳", "姻缘", "美酒"],
    answer: 0,
    analysis: "出自苏轼《水调歌头》，婵娟指月亮（或月光）。",
    tags: ["人文常识", "诗词"],
  },
  {
    id: "common-005",
    module: "common",
    type: "single-choice",
    stem: "我国现行宪法是哪一年颁布的？",
    options: ["1954", "1975", "1978", "1982"],
    answer: 3,
    analysis: "现行宪法为 1982 年宪法，此后有多次修正案。1954 是第一部宪法。",
    tags: ["宪法", "法治"],
  },
  {
    id: "common-006",
    module: "common",
    type: "single-choice",
    stem: "下列山脉中，属于我国地势第一、二级阶梯分界线的是：",
    options: ["大兴安岭", "太行山", "昆仑山", "雪峰山"],
    answer: 2,
    analysis:
      "一二级阶梯分界：昆仑山—祁连山—横断山。大兴安岭—太行—巫山—雪峰是二三级分界。",
    tags: ["地理", "地形"],
  },
  {
    id: "common-007",
    module: "common",
    type: "single-choice",
    stem: "市场经济条件下，宏观调控的主要手段是：",
    options: ["行政手段", "法律手段", "经济手段", "计划手段"],
    answer: 2,
    analysis: "宏观调控以经济手段（财政、货币）为主，法律和行政为辅。",
    tags: ["经济", "宏观调控"],
  },
  {
    id: "common-008",
    module: "common",
    type: "single-choice",
    stem: "下列不属于我国基本国策的是：",
    options: ["计划生育", "对外开放", "男女平等", "股份制改造"],
    answer: 3,
    analysis: "基本国策如计划生育、环境保护、对外开放、男女平等、节约资源等。股份制改造是经济改革措施。",
    tags: ["政治", "国策"],
  },
  {
    id: "common-009",
    module: "common",
    type: "single-choice",
    stem: "北斗卫星导航系统属于：",
    options: ["遥感系统", "全球卫星导航系统", "气象卫星系统", "通信卫星系统"],
    answer: 1,
    analysis: "北斗是我国自主建设、独立运行的全球卫星导航系统（GNSS）。",
    tags: ["科技", "航天"],
  },
  {
    id: "common-010",
    module: "common",
    type: "single-choice",
    stem: "《民法典》规定，向人民法院请求保护民事权利的普通诉讼时效期间为：",
    options: ["一年", "两年", "三年", "五年"],
    answer: 2,
    analysis: "《民法典》第 188 条：普通诉讼时效三年，自权利人知道或应当知道权利受损及义务人之日起计算。",
    tags: ["法律", "民法典"],
  },
  {
    id: "common-011",
    module: "common",
    type: "single-choice",
    stem: "下列河流中，最终注入太平洋的是：",
    options: ["塔里木河", "雅鲁藏布江", "黄河", "怒江"],
    answer: 2,
    analysis: "黄河注入渤海（太平洋）。塔里木河是内流河；雅鲁藏布江、怒江下游入印度洋。",
    tags: ["地理", "水文"],
  },
  {
    id: "common-012",
    module: "common",
    type: "single-choice",
    stem: "新发展理念的内容是：",
    options: [
      "创新、协调、绿色、开放、共享",
      "创新、效率、绿色、开放、公平",
      "发展、协调、生态、开放、共享",
      "创新、协调、低碳、包容、共享",
    ],
    answer: 0,
    analysis: "新发展理念：创新、协调、绿色、开放、共享。需准确记忆表述。",
    tags: ["政治理论", "新发展理念"],
  },
  {
    id: "common-013",
    module: "common",
    type: "single-choice",
    stem: "声音不能在下列哪种介质中传播？",
    options: ["空气", "水", "钢铁", "真空"],
    answer: 3,
    analysis: "声音是机械波，需要介质，真空中不能传播。",
    tags: ["科技常识", "物理"],
  },
  {
    id: "common-014",
    module: "common",
    type: "single-choice",
    stem: "下列历史事件按时间先后排列正确的是：",
    options: [
      "鸦片战争—辛亥革命—五四运动",
      "辛亥革命—鸦片战争—五四运动",
      "五四运动—辛亥革命—鸦片战争",
      "鸦片战争—五四运动—辛亥革命",
    ],
    answer: 0,
    analysis: "鸦片战争 1840；辛亥革命 1911；五四运动 1919。",
    tags: ["人文", "近现代史"],
  },
  {
    id: "common-015",
    module: "common",
    type: "single-choice",
    stem: "我国最大的淡水湖是：",
    options: ["洞庭湖", "太湖", "鄱阳湖", "洪泽湖"],
    answer: 2,
    analysis: "鄱阳湖是我国最大淡水湖（江西）；青海湖是最大湖泊（咸水）。",
    tags: ["地理", "湖泊"],
  },
];
