import type { InterviewQuestion } from "@/lib/types";

export const interviewQuestions: InterviewQuestion[] = [
  {
    id: "int-001",
    category: "analysis",
    title: "谈谈你对「躺平」现象的看法",
    stem: "近年来，部分青年中出现「躺平」「佛系」心态。请谈谈你的看法。",
    framework: [
      "表明态度：理解其社会成因，但不认同作为长期人生态度。",
      "分析原因：竞争压力、上升通道感知、评价体系单一。",
      "辩证影响：短期自我调节，长期不利于个人成长与社会活力。",
      "提出路径：个人理性规划 + 组织给舞台 + 社会多元评价。",
    ],
    pitfalls: [
      "一味批判年轻人「不上进」。",
      "只堆砌网络热词，没有分析。",
      "结尾空喊口号。",
    ],
    samplePoints: [
      "压力真实存在，应正视而不是贴标签。",
      "鼓励的是「有韧性的奋斗」，不是无效内卷。",
      "单位可通过清晰成长路径与容错机制回应青年关切。",
    ],
    suggestedSeconds: 180,
  },
  {
    id: "int-002",
    category: "analysis",
    title: "如何看待基层形式主义",
    stem: "有人说「基层负担重，很大程度是形式主义造成的」。你怎么看？",
    framework: [
      "承认现象：痕迹主义、重复报表、过度留痕确有存在。",
      "危害：挤占服务群众时间、挫伤积极性。",
      "根源：政绩观偏差、部门协同不足、技术工具滥用。",
      "对策：清单管理、数据共享、考核重实绩。",
    ],
    pitfalls: ["只批评不建设", "把所有问题都归因于「上级」"],
    samplePoints: ["一次填报、多方复用", "考核看结果与群众满意度"],
    suggestedSeconds: 180,
  },
  {
    id: "int-003",
    category: "analysis",
    title: "数字政务与老年人数字鸿沟",
    stem: "政务服务加速数字化，但部分老年人办事困难。请分析并提出建议。",
    framework: [
      "肯定数字化方向与必要性。",
      "指出问题：界面复杂、无健康码/手机、线下窗口减少。",
      "建议：保留线下兜底、亲友代办、社区帮办、适老化改造。",
    ],
    pitfalls: ["否定数字化", "只呼吁子女尽孝"],
    samplePoints: ["智慧与温度并行", "兜底服务不能撤"],
    suggestedSeconds: 150,
  },
  {
    id: "int-004",
    category: "plan",
    title: "组织一场政策宣讲进社区活动",
    stem: "单位要组织「惠民政策进社区」宣讲，领导交给你负责，你怎么组织？",
    framework: [
      "准备：摸清受众、选点、邀讲师、制作物料。",
      "宣传：公告栏、业主群、楼门长通知。",
      "现场：签到—宣讲—答疑—收集问题清单。",
      "收尾：未解决问题转办、总结反馈、评估效果。",
    ],
    pitfalls: ["只写流程没有对象意识", "忽略答疑与反馈"],
    samplePoints: ["用方言/案例讲政策", "设置咨询台一对一"],
    suggestedSeconds: 180,
  },
  {
    id: "int-005",
    category: "plan",
    title: "开展一次窗口服务满意度调查",
    stem: "领导让你对本单位窗口服务开展满意度调查，你怎么做？",
    framework: [
      "明确目的与指标（效率、态度、专业度、环境）。",
      "方法：现场问卷 + 电话回访 + 好差评系统。",
      "样本：业务类型分层，注意高峰/低谷时段。",
      "形成报告并提出可执行改进项。",
    ],
    pitfalls: ["问卷设计诱导性选项", "只报喜不报忧"],
    samplePoints: ["保护群众隐私", "改进项要对应责任科室"],
    suggestedSeconds: 180,
  },
  {
    id: "int-006",
    category: "plan",
    title: "筹备新同事入职培训",
    stem: "单位新进 10 名同事，领导让你筹备入职培训，你如何安排？",
    framework: [
      "需求调研：岗位、短板、培训目标。",
      "课程：规章制度、业务流程、廉政与保密、实操。",
      "形式：授课 + 轮岗体验 + 师带徒。",
      "考核与反馈，形成培训档案。",
    ],
    pitfalls: ["全是课堂灌输", "没有考核"],
    samplePoints: ["第一天破冰", "设置「问题清单」收集新人困惑"],
    suggestedSeconds: 150,
  },
  {
    id: "int-007",
    category: "interpersonal",
    title: "同事抢功且推责",
    stem: "你与同事合作完成项目，汇报时他把成绩说成自己的，问题推给你。你怎么办？",
    framework: [
      "冷静，避免当场冲突影响工作。",
      "私下沟通：对齐事实与分工，表达感受与期望。",
      "若再发生，用邮件/工作记录留痕，并向领导客观说明进展。",
      "反思协作机制：明确分工与同步节点。",
    ],
    pitfalls: ["忍气吞声不沟通", "直接越级告状情绪化"],
    samplePoints: ["对事不对人", "用数据说话"],
    suggestedSeconds: 150,
  },
  {
    id: "int-008",
    category: "interpersonal",
    title: "老同事坚持错误流程",
    stem: "老同事坚持用旧流程办事，效率低且有合规风险，你怎么与他沟通？",
    framework: [
      "尊重资历，先请教旧流程背后的考虑。",
      "用新规文件与风险案例说明差异。",
      "提供过渡方案：先并行试跑一周。",
      "必要时请领导或合规岗一起确认。",
    ],
    pitfalls: ["当众否定老同事", "强硬推行不顾情绪"],
    samplePoints: ["把「你的错」换成「我们怎么更稳」"],
    suggestedSeconds: 150,
  },
  {
    id: "int-009",
    category: "interpersonal",
    title: "群众投诉你态度不好",
    stem: "有群众投诉你办理业务时态度不好，但你认为自己按章办事。你怎么办？",
    framework: [
      "先平复情绪，感谢监督。",
      "复盘沟通方式，是否存在语气生硬、解释不清。",
      "主动回访致歉（对态度而非对原则），补充说明政策。",
      "提炼改进：多一句解释、给一张明白纸。",
    ],
    pitfalls: ["强调「我没错」拒绝沟通", "过度道歉放弃原则"],
    samplePoints: ["合规是底线，体验是标准"],
    suggestedSeconds: 150,
  },
  {
    id: "int-010",
    category: "emergency",
    title: "办事大厅系统崩溃",
    stem: "办事高峰时段系统突然崩溃，群众情绪激动，你怎么办？",
    framework: [
      "立即安抚：致歉、说明预计时间、提供饮水与座位。",
      "分流：可手写登记或延后办理的先分流。",
      "同步技术岗抢修，定期广播进展。",
      "恢复后加班延时，事后复盘应急预案。",
    ],
    pitfalls: ["只会说「等一等」", "不记录诉求导致二次投诉"],
    samplePoints: ["先稳情绪再稳秩序", "发放顺序号避免插队"],
    suggestedSeconds: 150,
  },
  {
    id: "int-011",
    category: "emergency",
    title: "检查中发现重大隐患",
    stem: "你带队检查，发现企业存在重大安全隐患且拒不整改，你怎么处理？",
    framework: [
      "固定证据，依法责令立即排除/停产停业。",
      "告知法律依据与后果，不搞私下妥协。",
      "报告上级，必要时联合执法。",
      "复查闭环，并开展警示教育。",
    ],
    pitfalls: ["人情执法", "只罚款不盯整改"],
    samplePoints: ["安全问题没有讨价还价空间"],
    suggestedSeconds: 150,
  },
  {
    id: "int-012",
    category: "emergency",
    title: "舆情突然发酵",
    stem: "关于你单位的一段短视频在网上引发负面舆情，领导让你处置，你怎么做？",
    framework: [
      "核实事实，不删帖对抗，不第一时间定性。",
      "统一口径，快速回应关切点。",
      "线下解决问题并同步进展。",
      "总结复盘，完善信息发布机制。",
    ],
    pitfalls: ["与网友对骂", "沉默到底"],
    samplePoints: ["回应速度与事实准确并重"],
    suggestedSeconds: 150,
  },
  {
    id: "int-013",
    category: "situational",
    title: "劝说违规占道经营的摊主",
    stem: "情景模拟：请现场劝说一位占道经营且家庭困难的摊主配合整改。",
    framework: [
      "称呼与共情：理解生计不易。",
      "讲清危害与规定：交通、消防、公平竞争。",
      "给方案：临时疏导点/时段经营/帮扶政策申请。",
      "留联系方式，约定复查时间。",
    ],
    pitfalls: ["上来就开罚", "只讲法不给路"],
    samplePoints: ["执法有力度，服务有温度"],
    suggestedSeconds: 180,
  },
  {
    id: "int-014",
    category: "situational",
    title: "安抚等待过久的办事群众",
    stem: "情景模拟：一位老人排队两小时仍未办理成功，非常生气，请你现场安抚并解决。",
    framework: [
      "起身迎接，道歉并请到休息区。",
      "快速判断卡点：材料不齐/流程不熟/系统问题。",
      "能当场办立即办；不能办给出书面清单与预约号。",
      "结束后说明如有困难可电话帮办。",
    ],
    pitfalls: ["反复解释规则打断对方", "让老人继续排队"],
    samplePoints: ["先解决情绪，再解决事情"],
    suggestedSeconds: 150,
  },
  {
    id: "int-015",
    category: "situational",
    title: "同事临场甩来紧急材料",
    stem: "情景模拟：下班前同事把一份紧急材料「甩」给你，说明天要，你如何回应？",
    framework: [
      "确认紧急程度与领导是否知情。",
      "评估手头优先级，给出可选方案（现在协助/明天早班/请领导协调）。",
      "若接，明确格式、数据来源与截止点。",
      "完成后同步，避免再次临时甩锅。",
    ],
    pitfalls: ["直接拒绝伤关系", "全盘接下导致自己崩盘"],
    samplePoints: ["把情绪沟通换成方案沟通"],
    suggestedSeconds: 120,
  },
];

export function interviewByCategory(
  cat: InterviewQuestion["category"]
): InterviewQuestion[] {
  return interviewQuestions.filter((q) => q.category === cat);
}

export function getInterview(id: string): InterviewQuestion | undefined {
  return interviewQuestions.find((q) => q.id === id);
}
